from django.urls import path

from . import views

urlpatterns = [
    path('media/<path:path>', views.ProtectedMediaView.as_view(), name='protected_media'),
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('ajuda/', views.HelpView.as_view(), name='help'),

    path('contratos/', views.ContractListView.as_view(), name='contract_list'),
    path('contratos/novo/', views.ContractCreateView.as_view(), name='contract_create'),
    path('contratos/<int:pk>/', views.ContractDetailView.as_view(), name='contract_detail'),
    path('contratos/<int:pk>/editar/', views.ContractUpdateView.as_view(), name='contract_update'),
    path('contratos/<int:pk>/excluir/', views.ContractDeleteView.as_view(), name='contract_delete'),

    path('empresas/', views.SupplierListView.as_view(), name='supplier_list'),
    path('empresas/nova/', views.SupplierCreateView.as_view(), name='supplier_create'),
    path('empresas/<int:pk>/editar/', views.SupplierUpdateView.as_view(), name='supplier_update'),
    path('organizacoes/', views.OrganizationListView.as_view(), name='organization_list'),
    path('organizacoes/nova/', views.OrganizationCreateView.as_view(), name='organization_create'),
    path('organizacoes/<int:pk>/editar/', views.OrganizationUpdateView.as_view(), name='organization_update'),
    path('responsaveis/', views.PersonListView.as_view(), name='person_list'),
    path('responsaveis/novo/', views.PersonCreateView.as_view(), name='person_create'),
    path('responsaveis/<int:pk>/editar/', views.PersonUpdateView.as_view(), name='person_update'),

    path('itens/novo/', views.ItemCreateView.as_view(), name='item_create'),
    path('itens/<int:pk>/editar/', views.ItemUpdateView.as_view(), name='item_update'),
    path('itens/<int:pk>/excluir/', views.ItemDeleteView.as_view(), name='item_delete'),
    path('empenhos/', views.CommitmentListView.as_view(), name='commitment_list'),
    path('empenhos/novo/', views.CommitmentCreateView.as_view(), name='commitment_create'),
    path('empenhos/<int:pk>/editar/', views.CommitmentUpdateView.as_view(), name='commitment_update'),
    path('empenhos/<int:pk>/excluir/', views.CommitmentDeleteView.as_view(), name='commitment_delete'),
    path('ordens/', views.SupplyOrderListView.as_view(), name='supplyorder_list'),
    path('ordens/nova/', views.SupplyOrderCreateView.as_view(), name='supplyorder_create'),
    path('ordens/<int:pk>/editar/', views.SupplyOrderUpdateView.as_view(), name='supplyorder_update'),
    path('ordens/<int:pk>/excluir/', views.SupplyOrderDeleteView.as_view(), name='supplyorder_delete'),
    path('entregas/', views.DeliveryListView.as_view(), name='delivery_list'),
    path('entregas/nova/', views.DeliveryCreateView.as_view(), name='delivery_create'),
    path('entregas/<int:pk>/editar/', views.DeliveryUpdateView.as_view(), name='delivery_update'),
    path('entregas/<int:pk>/excluir/', views.DeliveryDeleteView.as_view(), name='delivery_delete'),
    path('alteracoes/', views.ChangeListView.as_view(), name='change_list'),
    path('alteracoes/nova/', views.ChangeCreateView.as_view(), name='change_create'),
    path('alteracoes/<int:pk>/editar/', views.ChangeUpdateView.as_view(), name='change_update'),
    path('alteracoes/<int:pk>/excluir/', views.ChangeDeleteView.as_view(), name='change_delete'),
    path('paai/', views.ProcessListView.as_view(), name='process_list'),
    path('paai/novo/', views.ProcessCreateView.as_view(), name='process_create'),
    path('paai/<int:pk>/editar/', views.ProcessUpdateView.as_view(), name='process_update'),
    path('paai/<int:pk>/excluir/', views.ProcessDeleteView.as_view(), name='process_delete'),
    path('documentos/', views.DocumentListView.as_view(), name='document_list'),
    path('documentos/novo/', views.DocumentCreateView.as_view(), name='document_create'),
    path('documentos/<int:pk>/editar/', views.DocumentUpdateView.as_view(), name='document_update'),
    path('documentos/<int:pk>/excluir/', views.DocumentDeleteView.as_view(), name='document_delete'),
    path('auditoria/', views.AuditListView.as_view(), name='audit_list'),

    path('importar/', views.ImportUploadView.as_view(), name='import_upload'),
    path('importar/modelo/', views.DownloadImportTemplateView.as_view(), name='import_template'),
    path('importar/<int:pk>/previa/', views.ImportPreviewView.as_view(), name='import_preview'),
    path('importar/<int:pk>/cancelar/', views.ImportCancelView.as_view(), name='import_cancel'),

    path('relatorios/contratos.csv', views.ExportContractsCsvView.as_view(), name='export_contracts_csv'),
    path('relatorios/contratos.xlsx', views.ExportContractsXlsxView.as_view(), name='export_contracts_xlsx'),
    path('relatorios/contratos.pdf', views.ExportContractsPdfView.as_view(), name='export_contracts_pdf'),
]
